### PR TITLE
Updates to support two simultaneous web servers (http, https)

### PR DESCRIPTION
**Pull request by arrmo**
Each with Auth as an option.

### CODE REVIEW

**Comment by tagyoureit** [comment]
I merged the code locally on my system, and... Sweet!  I have achieved two servers running at the same time on the system.  

I do see some things that need cleaning up, but really like your approach.  One minor item is `path` doesn't need to be put in an array, it's just a reference to a module.  The other is the line
```
srvDesired += container.settings.get(currServer + 'Enabled');
```
If the settings are something like `http:1, https:0`, this will keep `srvDesired` at the value of 0 and over-write the http server. 

I'll clean up some of these minor items, test them out, and get socket.io running.  Stay tuned!

**Comment by arrmo** [comment]
Glad it works for you! It is working here ... so I have external world access (https and auth), as well as getting through SmartThings issues. Best of both worlds ... :-).

I agree with you on path. I got over-zealous ... LMAO.

Not so sure I agree on the comment about srvDesired - but I may be wrong! The idea is to count the number of desired servers, and then not resolve() until that number is opened. As for the array, no over-write ... they are just two indexed elements. Thoughts?

**Comment by arrmo** [comment]
BTW, srvDesired also helps when shutting down => again, don't resolve() until the number shut down matches the desired number of servers.

**Comment by tagyoureit** [comment]
> Not so sure I agree on the comment about srvDesired - but I may be wrong! The idea is to count the number of desired servers, and then not resolve() until that number is opened. As for the array, no over-write ... they are just two indexed elements. Thoughts?

This isn't exactly right.  The resolve() method only returns a value back to another execution loop.  Think of it more like a return statement on synchronous code.  The fact that we do (or do not) call resolve() does not change the fact that the Express server has not already started.  So there are two side effects here, one is that the index isn't incremented if we have https.enabled=0, and that the second server will try to start anyway even though we never return a promise (or reject it).  

I think if we always treat the arrays as having the values `[http stuff, https stuff]` then it might sit better with me.  For example, `server[0]` is always http and `server[1]` is always https.  

I think I understand why this is working, but let me explain why it also wouldn't be technically correct for only one server.
```
				server[iter].listen(port[iter], function () {
					container.logger.verbose('Express Server ' + currServer + ' listening at port %d', port[iter]);
					srvActive += 1;
					if (srvActive === srvDesired)
						resolve();
				});
```
Why is it working (with two servers)?  At the beginning of the promise, we increment the srvDesired count.  The srvActive+=1 line, because of the server listener callback, has only a slight delay while the server is starting up.  Before it actually starts, we go back to the loop and increment srvDesired again.  I think we are taking advantage here of a timing issue but it might not be guaranteed that, in all cases, that the for loop runs faster than the server starting up.

Why isn't it technically working (with only http)?  Because it is still trying to start up the https server.  The way the code is written, when we do not want to start up the https server, we do not increment the srvDesired count, so the promise is returned after the http server starts up, but... that isn't preventing the call to `server[iter] = container.https.createServer(opt_https, app[iter]);`.  So we have a https server running that we aren't tracking.  Make sense?

I think there is a slight mismatch to return a promise early in a for loop based on conditions, when the for loop will still run after the promise is resolved.

**Comment by arrmo** [comment]
I think you're right! I meant to add in a check, only set up the server if it's enabled ... but I missed that check ... :-).

Good catch, thanks!

And yes BTW - I was assuming that no matter what, index 0 was for http, 1 for https.

**Comment by tagyoureit** [comment]
Ok, I just pushed up this PR.  I changed more than I had anticipated.  We also don't need an array of Express servers, and then I put the port/server/app inside a JSON object because that was how I coded the Socket.IO part first and realized your array approach wasn't as compatible as I thought (and I'm more comfortable with the JSON object, but same thing at the end of the day).  So thanks!  I tested the different scenarios manually, and will work on testing with the test suite, but wanted to push it out.

I also added the http redirect to https in case anyone wants that.

**Comment by arrmo** [comment]
Testing here ... FYI, there is an error in config.json, row 188 (trailing comma) => agreed? At least here when I remove it, then things proceed.

After that - it seems to work, thanks!

BTW, I have made some local changes to index.html, not referencing cdnjs.cloudflare.com, rather pulling the files local (they were the only ones reference remotely, and that causes security failures for me). You OK with a PR to pull these in local as well?

**Comment by tagyoureit** [comment]
> Testing here ... FYI, there is an error in config.json, row 188 (trailing comma) => agreed? At least here when I remove it, then things proceed.

Ugh, yeah.

> BTW, I have made some local changes to index.html, not referencing cdnjs.cloudflare.com, rather pulling the files local (they were the only ones reference remotely, and that causes security failures for me). You OK with a PR to pull these in local as well?

Yes on this, too.  I updated clientConfig.json because the decrement (spa/pool heat) was -1 and the way I coded it was expecting a positive number (eg a decrement of -1 degrees was actually an increase of 1 degree... two negatives making a positive.)

**Comment by arrmo** [comment]
OK, PR #72 created (for index.html, bootstrap-select).

Do you want to take care of the comma, or I can push it - just let me know.

Thanks!

**Comment by tagyoureit** [comment]
I fixed the comma already.  I'll add a check to try to read the file and throw and error if it doesn't parse.  Thanks!

**Pull request merged**
