### PR TITLE
Update EquipmentStateMessage.ts

### PR DESCRIPTION
**Pull request by bkhall**
Fix model label of IntelliTouch i5+3 systems

### CODE REVIEW

**Comment by bkhall** [comment]
I made this change on my local system and recompiled and now my system is identified correctly. I chose case 0 instead of case 3, because of the number of allowed bodies - case 0 has 2 and case 3 has 1.

**Comment by tagyoureit** [comment]
This could be correct, but I'd need to see the communications between your OCP and njsPC.  Could you please open up an issue and attach a packet capture so I can verify if you've done this correctly?

**Comment by bkhall** [comment]
Can I just attach it here?

**Comment by tagyoureit** [comment]
Sure.

**Comment by bkhall** [comment]
[replay.zip](https://github.com/tagyoureit/nodejs-poolController/files/5788367/replay.zip)
As requested

**Comment by tagyoureit** [comment]
Unfortunately, I'm not able to open the zip.  Some of the browsers now cause CRC errors when you download them.  You can find the same file /nodejs-poolController/logs directory.  Can you please retrieve from there, double check you can unzip, and attach again?

**Comment by bkhall** [comment]
I reattached it...above

**Comment by tagyoureit** [comment]
Hi @bkhall.  All looks good.  We have been working fervently on the `next` branch which is about 80 commits ahead.  I manually added your changes there instead of trying to merge the history for the 80 different commits.  Feel free to keep your local changes or switch over to the `next` branch to download this fix.  I'll be pushing 6.x to master likely in the next couple weeks once we get the chemController stuff solid.

**Pull request closed without merging**
