### PR TITLE
allowing for schedules where start time > end time

### PR DESCRIPTION
**Pull request by CodeSlinger69**
For example, if a schedule is set to start at sunset, and end at sunrise, the start time might be 20:30 and the end time might be 05:10. As this schedule crosses the midnight boundary, different logic is required when comparing to the current time.

These changes handle the above situation, and all other variants of start time and end time, manual/sunrise/sunset, and the case where start time == end time.

### CODE REVIEW

**Comment by rstrouse** [comment]
I completely and unintentionally goofed your PR, git requires bit of a voodoo sometimes when there are other PRs stacked up.  This one included files from prior PRs.  I will manually add your changes to the repo.

**Comment by rstrouse** [comment]
I am trying to figure out why you are trying to turn on a circuit when the user explicitly turned off the circuit.  This should not be so.  At any point you should be able to manually turn off a circuit and the controller should not manually turn it back on again.  If you do turn it back on and manual priority is not set then it should automatically turn it off when the schedule expires.

**Comment by CodeSlinger69** [comment]
Glad I'm not the only one not entirely fluent on git and github functions. 

This PR in particular is not about manually turning on a circuit, but about handling a schedule that goes from 11pm to 6am, or from sunset to sunrise. As I mentioned over [here](https://github.com/tagyoureit/nodejs-poolController/pull/813), I'm totally OK with the design choice to NOT allow schedules that cross midnight. In which case, this PR should be cancelled.

I think you're comments refers to [this PR,](https://github.com/tagyoureit/nodejs-poolController/pull/813) where I attempt to correct for the situation where one schedule turns off and another turns on within the same 3000ms polling window. Like you mentioned in that thread however, there are additional complexities, and that might not be the best place to fix it.

**Comment by CodeSlinger69** [comment]
Closing this due to learning that njsPC had a design decision to NOT allow schedules to cross the midnight boundary.

**Pull request closed without merging**
