### PR TITLE
To fix UI Issue (Button Sizes)

### PR DESCRIPTION
**Pull request by arrmo**

### CODE REVIEW

**Comment by tagyoureit** [comment]
I'm getting this error on load:
```
TypeError: undefined is not an object (evaluating 'data.result.capitalizeFirstLetter')   main.js:572
```

**Comment by arrmo** [comment]
Really? Hmmm ... not seeing it here. I do find that refresh is often not getting a reply from the server, but looking at the console here, no errors at all. Very odd.

Any more details?

Thanks!

**Comment by tagyoureit** [comment]
I reloaded, and it worked the second time... on a few subsequent calls I was back to the `ReferenceError: Can't find variable: generalParams mainjs:387` error.  

The problem could be that the browser is receiving (or processing) the socket calls in a strange order?  Or the configClient.json is being read (or finished reading) after the sockets are received?  Not sure, but you might need to put some checks to make sure that you have the actual data you need (e.g.... if (data!==undefined), etc?  I'll also check on my end to make sure everything is being sent out, though.

**Comment by tagyoureit** [comment]
Two thoughts,  neither of which is really ideal...
1.  I put a small delay before emitting the socket upon connection
2. You utlilize the 'all' (or 'one'?  I forget the act name now) socket which all the info together. 

Maybe with the first one we could test at least to see if it is a timing issue.

**Comment by arrmo** [comment]
What's interesting is that it's handled in a callback - so not processed until the JSON has been returned ... right? And of of that is inside jQuery document ready. Hmmm ... 

OK, found it! It seems that circuit is being sent back before the JSON file has been returned / retrieved. Yep, that would cause it. I can ignore the circuit feedback until the JSON (clientConfig.json) is sent ... but then is there a way I can retrigger sending the (circuit) information?

**Comment by tagyoureit** [comment]
Ok... I tested with a small delay and it does work.    
At line https://github.com/tagyoureit/nodejs-poolController/blob/3.1.x-DEV/src/lib/comms/socketio-helper.js#L330 I replaced that with 
```
            setTimeout(emitToClients, 100, 'all')
```

This is 0.1s delay, so barely noticeable on the client side.  (I could test shorter delays as well, but don't need to be that precise, I think.)  In "best practice", the client (bootstrap) should probably make sure to load all local css/js files and _then_ connect to socket.io.  But I'm ok leaving it this way (unless you get the itch to fix it on your end).  Test it out and let me know on your end.  

Still weird you aren't seeing any console errors... what browser are you testing on?

**Comment by tagyoureit** [comment]
Quick update... the small delay is causing some of my tests to fail... so I had a thought to just check the order of resources that are loading.  Socket.io is loading before main.js.  Changing the order to
```
	<script src="js/bootstrap.min.js"></script>
	<script src="main.js"></script>
	<script src="../socket.io/socket.io.js"></script>
```
loads the socket last.  And if 15 page reloads in Safari (without the aforementioned socket delay on the server side) it also loads perfectly now.  So maybe this small change will be the solution?

**Comment by arrmo** [comment]
That would make sense. If you push it up I'll check also.

BTW, sorry if I confused you earlier - I do see errors, in the loading fail case. I thought you meant when things loaded correctly. But it seems we are on the same page.

**Comment by tagyoureit** [comment]
Too many open issues to keep them all straight!  The more process we make, the further we want to push (and the more things we need to fix along the way).  But it's looking so awesome right now.  Much thanks!

**Comment by arrmo** [comment]
Never mind, confused here also - I realize you mean on the client side. I'll take care of it!

**Comment by arrmo** [comment]
OK, struggling a bit with this one. Figured I'd delay initializing the socket.it until the configuration data is received, but that doesn't work ... I really need emit early on (to handle / control config data), but don't want socket traffic back quite yet ... :-).

That said, what triggers you sending the configuration (temperatures, pumps, etc.)? Perhaps I can control it then.

**Comment by arrmo** [comment]
OK, I think I have this fixed - and I actually like it, as it forces / controls the sequencing properly ... I think ... ;-).

It's in PR #37 - please test it out, let me know. Thanks!

**Comment by tagyoureit** [comment]
Glad you got it working!  I'll do a little more testing, but looks good.

> That said, what triggers you sending the configuration (temperatures, pumps, etc.)? Perhaps I can control it then.

The first time everything is sent is `.on('connect')...` so immediately when any client phones home it gets all the data.  After that, each individual socket is sent only when there is a change in the data.  For the time, it would be every minute, for example.  The only real exception to this is the pump status.  The RPM/watts fluctuates very often so I put some logic in place to only send these socket updates when theres is a change in value of 5% or more.

**Pull request merged**
