### PR TITLE
support last-will-and-testament for MQTT

### PR DESCRIPTION
**Pull request by ccutrer**
and also configure Home Assistant availability topics to use it

### CODE REVIEW

**Comment by tagyoureit** [comment]
Hi, and thanks for submitting this.  Couple questions.

1. On `controller/boards/SystemBoard.ts` We are only using values of 0, 1 and 2 in the code.  I don't see any places we are actually setting the error value.  This means that we won't ever set a "lost" status either.  When were you hoping to have a lost status sent?
2. In the `web/bindings/mqtt.json` you have the willPayload hardcoded and then are sending it here `https://github.com/tagyoureit/nodejs-poolController/pull/611/files#diff-18e95f56ff9eafa4866db0f4a28be11e3a8df1ddd6a2c7132e5dedb4b2a27391R227` but it never changes.  Is it supposed to be hardcoded to value 3=lost?

**Comment by ccutrer** [comment]
1. Correct. See 2.
2. Correct. I figured hardcoded is fine, because it doesn't need to be/can't be dynamic. Because of this, I didn't think it was worth the effort to figure out how to get the byteValueMap plumbed and substituted in. But I did want to "document" the new possible value over in the definition for controllerStatus. This is still a config file, and a use could override the willPayload if they want.

If you want to avoid the duplication, I'd be more than happy to change it, but I might need some pointers on how to plumb it through. Java/TypeScript isn't my first (or second or third) language.

**Comment by tagyoureit** [comment]
Can you pull out the changes from systemboard?  Those are for communications between the OCP and njsPC.  It looks like you are trying to set the LWT message for when njsPC disconnects from MQTT.  Is that correct?

**Comment by ccutrer** [comment]
> Can you pull out the changes from systemboard? Those are for communications between the OCP and njsPC. It looks like you are trying to set the LWT message for when njsPC disconnects from MQTT. Is that correct?

Yup,  I want to be able to easily show that njsPC is no longer communicating with my HA System, for whatever reason. I've backed out the system board changes, and updated the PR.

**Pull request merged**
