### PR TITLE
Add circuit to socketISY.js variables

### PR DESCRIPTION
**Pull request by mayermd**
This pull requests adds the ability to sync circuit properties to ISY variables, much like the chlorinator and pump functionality.

### CODE REVIEW

**Comment by tagyoureit** [comment]
Hi,
thanks for contributing!  A past user helped put this together (and I don't have ISY), so thanks for giving it some attention.  I can also update this for the 4.x-DEV branch which is under active development.  Before I accept this PR, can you see the [contributing](https://github.com/tagyoureit/nodejs-poolController/blob/master/CONTRIBUTING.md) docs and send me back the [CLA](https://github.com/tagyoureit/nodejs-poolController/blob/master/CLA.txt).  

If that's too much of a pain, I can make these changes without accepting the PR.

thanks,
Russ

**Comment by mayermd** [comment]
I apologize for missing that step...Please find my signed CLA attached.
Please let me know if you need anything else from me.

Thank You

Mike Mayer

**Comment by tagyoureit** [comment]
Accepted.  I also updated the code for the 4.x-DEV branch as I mentioned.  See #57 for small changes in reading the data structures, but otherwise it should work.  Thanks!

**Comment by brianmtreese** [comment]
Hey @mayermd, It looks like you've headed down this path, I'm working through an ISY set up and am not exactly sure what I need to do on the ISY end. If you have any examples or pointers I would greatly appreciate them. Thanks!

**Comment by mayermd** [comment]
Brian,
The integration with the ISY just updates state variables in the ISY.  Then you write programs, etc in the ISY that react to state variable changes.  Set the socketISY integration setting to 1 in the pool controller config, create the State variables you are interested in tracking in the ISY console, then update the circuit/pump assigned variables to your state variable number in the pool controller config.  As values change in the pool controller they will update the ISY variables accordingly.  I have taken it a step further and call the REST api for the pool controller from ISY network integrations to toggle lights, fountains etc.  Below is my ISY config.  The numbers to the right of the circuit and pump variables are the variable ID's of my state variables in the ISY.  You can name the variables whatever you want, you just have to enter the corresponding ID in the pool controller config.

"integrations": {
        "socketISY": 1,
        "outputSocketToConsoleExample": 0
    },
    "socketISY": {
        "username": "<isy username",
        "password": "<isy password>",
        "ipaddr": "<ip of isy>",
        "port": 80,
        "Variables": {
            "circuit": {
                "2": {
                    "status": 3
                },
                "3": {
                    "status": 2
                }
            },
            "pump": {
                "1": {
                    "watts": 4,
                    "rpm": 5,
                    "currentprogram": 7,
                    "power": 6
                }
            }
        }
    }


Hope that helps, let me know if you have any questions..

Thanks 
Mike

**Comment by brianmtreese** [comment]
@mayermd thanks so much for your explanation! I was almost there, I was just missing that the value was the id from the ISY state variable. Thanks for taking the time to help, I very much appreciate it!

**Comment by brianmtreese** [comment]
Hey @mayermd so I have everything set up to update variables in the ISY and everything works great. It's awesome to be able to do that. But, now I'm wanting to go the other way and have the ISY control the pool controller like your set up wher you mention using the REST api. I've been looking into alot and am not exactly sure how to set that up. Did you use custom Node Servers in the ISY? Do you have any examples that you'd be cool with sharing? I'm not really a programmer so I have struggled my way through some things but have been unable to set anything up that works. I'd greatly appreciate any advice you may have. Thanks!

**Comment by mayermd** [comment]
Hey brianmtreese,

Sorry for the delay, I've been a little out of pocket.  To make this work you have to have the network module installed in the ISY.  It is a separate purchase from Universal Devices.  Once that is installed you will have a network tab in the configuration section of the ISY client.  Under that you will have a network Resources tab.  You can create a network resource that calls the REST api in the pool controller.  I have an example below.  You can call the network resource from programs and it will execute the REST command. The only problem with this approach is the the rest api toggles the circuit.  It doesn't have discrete on and off commands.  But now that you have the state variables in your ISY you can check if the state is the opposite of what you want before you call the toggle command.

screen shot 2018-03-09 at 3 53 38 pm
screen shot 2018-03-09 at 3 59 28 pm

Hope that helps.  Let me know if you have questions.

Thanks
Mike

**Comment by brianmtreese** [comment]
Mike, thanks so much for your help! Thanks to your info I was able to get this set up and working! I'm actually using 5.x firmware and am looking into creating a node server for the pool controller. If I can figure it out I'll let you know. Thanks again, I really appreciate it!

**Comment by brianmtreese** [comment]
Hey Mike, just wanted to let you know that I've created a Polyglot NodeServer for the nodejs pool controller if you want to give it a try: https://github.com/brianmtreese/nodejs-pool-controller-polyglotv2. It's working pretty well for me right now.

**Pull request merged**
